# Generated by Django 6.0.5 on 2026-05-06 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Well',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('depth_data', models.JSONField()),
                ('density_log', models.JSONField()),
                ('resistivity_log', models.JSONField()),
            ],
        ),
    ]
